shw_hlp_msg = [ \
    "show task list",
    '---',
    '- usage : shw task [options]',
    '---',
    '- options',
    '---',
    ("-t, --task [task name]"       , "filter by task name (support comma sep)"),
    ("-y, --task_type [task type]"  , "filter by task task type (support comma sep)"),
    ("-s, --status [ACT|TRM]"       , "filter by task task status (support comma sep)"),
    ("-a, --act-status [OK|ABN]"    , "filter by task task act status (support comma sep)"),
    ("-p, --pid [PID NUMBER]"       , "filter by task task pid (support comma sep)"),
    "---",
    "- example",
    "---",
    ("shw task -y process"          , "show process type task"),
    ("shw task -a ABN"              , "show process which act status is ABN")
]

shw_status_hlp_msg = [ \
    "show task's status",
    '---',
    '- usage : shw status [task_name | all]',
    '---',
    '- options',
    '---',
    'no options',
    "---",
    "- example",
    "---",
    ("shw status"          , "show all task's status"),
    ("shw status ps05"              , "show ps06 task's status")
]

shw_recovery_hlp_msg = [ \
    "show recovery result list",
    '---',
    '- usage : shw recovery',
    '---',
    '- options',
    '---',
    'no options',
    "---",
    "- example",
    "---",
    ("shw recovery"          , "show all recovery result"),
]

shw_ready_hlp_msg = [ \
    "show task ready status",
    '---',
    '- usage : shw ready [task_name]',
    '---',
    '- options',
    '---',
    'no options',
    "---",
    "- example",
    "---",
    ("shw ready ps01"          , "show ps01's ready status"),
]

set_hlp_msg = [ \
    'set new task',
    '---',
    '- usage : set task [task_type]:[task_name]:[task_command], ...',
    '---',
    '- options',
    '---',
    'no options',
    '---',
    '- example',
    '---',
    ( 'set task process:p:python t.py', "set new task p, that run t.py"),
    '---',
    '- description',
    '---',
    '* you can use multiple stdin with "," sep.',
]

set_recovery_hlp_msg = [\
    'run recovery',
    '---',
    '- usage : set recovery [task_name]:[message], ...',
    '---',
    '- options',
    '---',
    'no options',
    '---',
    '- example',
    '---',
    ( 'set recovery p1:run recover', "create new recovery process and send 'run recover' message"),
    '---',
    '- description',
    '---',
    '* you can use multiple stdin with "," sep.',
]

del_hlp_msg = [ \
    'del existing task',
    '---',
    '- usage : del task [task_name], ...',
    '---',
    '- options',
    '---',
    'no options',
    '---',
    '- example',
    '---',
    ( 'del task p1', "delete task 'p1' and remove"),
    ( '', "and remove all data which relation with task 'p1'"),
    '---',
    '- description',
    '---',
    '* you can use multiple stdin with "," sep.',
]

act_hlp_msg = [ \
    'act existing task',
    '---',
    '- usage : act [task_name], ...',
    '---',
    '- options',
    '---',
    'no options',
    '---',
    '- example',
    '---',
    ( 'act p1', "act task 'p1'"),
    '---',
    '- description',
    '---',
    '* you can use multiple stdin with "," sep.',
]

trm_hlp_msg = [ \
    'term existing task',
    '---',
    '- usage : trm [task_name], ...',
    '---',
    '- options',
    '---',
    'no options',
    '---',
    '- example',
    '---',
    ( 'trm p1', "term task 'p1'"),
    '---',
    '- description',
    '---',
    '* you can use multiple stdin with "," sep.',
]
